<?php
# This file was automatically generated by the MediaWiki 1.19.20
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename      = "Elexis-Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "wiki";
$wgScriptExtension  = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer           = "http://wiki.elexis.info";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "/config/elexis_135.png";


## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "apache@localhost:8888";
$WGPasswordSender   = "apache@localhost:8888";

$wgEnotifUserTalk      = false; # UPO
$wgEnotifWatchlist     = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "mysql";
$wgDBname           = "elexis_wiki";
$wgDBuser           = "elexis";
$wgDBpassword       = "";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType    = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgAllowCopyUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

## To enable image uploads, make sure the 'images' directory
# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "C.UTF-8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "de-ch";

$wgSecretKey = "5a6de5d5178c1048b498024fbe69e7d011aa7824170901dea5035dd609664634";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "54bb6db5a25a0809";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;



# End of automatically generated settings.
# Add more configuration options below.

$wgScriptPath       = "";
$wgScriptPath	    = "";
$wgArticlePath      = "/$1";
$wgUsePathInfo      = true;
$wgAllowImageMoving = true;
$wgGroupPermissions['Trusted']['move']          = true;
$wgGroupPermissions['Trusted']['movefile']      = true;

wfLoadSkin( 'CologneBlue' );
wfLoadSkin( 'Modern' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Vector' );

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['user']['edit'] = false;
$wgGroupPermissions['sysop']['edit'] = true;
$wgGroupPermissions['sysop']['delete'] = true;
$wgGroupPermissions['Trusted']['delete'] = true;
$wgGroupPermissions['Trusted'] = $wgGroupPermissions['user'];
$wgGroupPermissions['user'   ]['edit']          = false;
$wgGroupPermissions['Trusted']['edit']          = true;

# Enabled Extensions. Most extensions are enabled by including the base extension file here
# but check specific extension documentation for more details
# The following extensions were automatically enabled:
require_once( "$IP/extensions/ConfirmEdit/ConfirmEdit.php" );
# wfLoadExtension("ConfirmEdit/ConfirmEdit");
# wfLoadExtension("LanguageSelector/LanguageSelector");
require_once( "$IP/extensions/LanguageSelector/LanguageSelector.php" );

# The following to extension don't work with 1.24.3
# require_once("Collection/Collection");
# The following extensions require at lease 1.25
# wfLoadExtension("WikiEditor/WikiEditor");
# wfLoadExtension("Nuke/Nuke");)

$wgFileExtensions = array('png','gif','jpg','jpeg', 'pdf', 'tiff','bmp', 'odt','ods','odp','odg');
# $wgFileExtensions = array('png','gif','jpg','jpeg', 'pdf', 'ods, 'odt', 'PNG', 'JPG');
# $wgFileBlacklist = array_diff( $wgFileBlacklist, array ('png') );

# See http://www.mediawiki.org/wiki/Extension:BlockAndNuke
# require_once( "$IP/extensions/BlockAndNuke/BlockAndNuke.php" );
#wfLoadExtension("BlockAndNuke/BlockandNuke");
$wgWhitelist = ("$IP/extensions/BlockAndNuke/whitelist.txt");


# $wgLanguageSelectorLanguages=array("en", "de-ch");
# $wgLanguageSelectorLocation = LANGUAGE_SELECTOR_NONE;
$wgLanguageSelectorLocation = LANGUAGE_SELECTOR_USE_CONTENT_LANG;

$wgCollectionPODPartners = false;
#$wgCollectionMWServeURL = 'http://wiki.elexis.info:8898/cache';
# $wgCollectionMWServeCredentials = "elexis:F@d9J52azXn6";

$wgEnableAPI = true;



