#!/bin/bash -v
set -e
set -x
# Small helper script. Please look at the README.md for further explanation
export FQDN=demo1.testbed-elexis.dyndns.org
# end of configuration

# create valid certificate using letsencrypt
# sudo  apt-get install letsencrypt.sh
# wget https://raw.githubusercontent.com/lukas2511/dehydrated/master/docs/examples/config
if false # don't know why letsencrypt do not work
then
  echo $FQDN > domains.txt
  cp /usr/share/doc/letsencrypt.sh/examples/config.sh.example ./config
  letsencrypt.sh -f  ./config --out . -c
  cp   $FQDN/cert.pem noVNC/self_letsencrypt.pem
fi

# openssl req -batch -new -x509 -days 365 -nodes -out noVNC/self.pem -keyout noVNC/self.pem -/CN=$FQDN
for INDEX in 1 2 3 4 5
do
  PEMFILE=noVNC/self$INDEX.pem
  if [ ! -f $PEMFILE ]
  then
    cmd="openssl req -batch -new -x509 -subj /CN=demo$INDEX.testbed-elexis.dyndns.org -days 365 -nodes -out $PEMFILE -keyout $PEMFILE"
    echo cmd is $cmd
    eval $cmd
  fi
done

docker build -t docker-eclipse-novnc .
docker-compose build
docker-compose create
