# docker-elexis-nvnc
version: '2.0'
services:
  demo_de_ch_a:
    build: .
    environment:
      VNCPASS:  elexis
      PEMFILE:  self1.pem
      NL: de_CH
    domainname: testbed-elexis.dyndns.org
    hostname: demo_de_ch_a
    ports:
      - "6081:6080"


  demo_de_ch_b:
    build: .
    environment:
      VNCPASS:  elexis
      PEMFILE:  self2.pem
      NL: de_CH
    domainname: testbed-elexis.dyndns.org
    hostname: demo_de_ch_c
    ports:
      - "6082:6080"


  demo_de_ch_c:
    build: .
    environment:
      VNCPASS:  elexis
      PEMFILE:  self3.pem
      NL: de_CH
    domainname: testbed-elexis.dyndns.org
    hostname: demo_de_ch_a
    ports:
      - "6083:6080"

  demo_it_ch_a:
    build: .
    environment:
      VNCPASS:  elexis
      PEMFILE:  self1.pem
      NL: it_CH
    domainname: testbed-elexis.dyndns.org
    hostname: demo_it_ch_a
    ports:
      - "6181:6080"


  demo_it_ch_b:
    build: .
    environment:
      VNCPASS:  elexis
      PEMFILE:  self2.pem
      NL: it_CH
    domainname: testbed-elexis.dyndns.org
    hostname: demo_it_ch_c
    ports:
      - "6182:6080"


  demo_it_ch_c:
    build: .
    environment:
      VNCPASS:  elexis
      PEMFILE:  self3.pem
      NL: it_CH
    domainname: testbed-elexis.dyndns.org
    hostname: demo_it_ch_a
    ports:
      - "6183:6080"

  demo_fr_ch_a:
    build: .
    environment:
      VNCPASS:  elexis
      PEMFILE:  self1.pem
      NL: it_CH
    domainname: testbed-elexis.dyndns.org
    hostname: demo_fr_ch_a
    ports:
      - "6281:6080"

